# Generated by Django 4.0.2 on 2022-04-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('author_email', models.EmailField(max_length=254)),
                ('review_title', models.CharField(max_length=300, null=True)),
                ('review_body', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('sentiment_score', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
    ]
